name: bluetooth_print
description: BluetoothPrint is a bluetooth plugin to help developers build bluetooth thermal printer apps for both iOS and Android.
version: 4.3.0
homepage: https://github.com/thon-ju/bluetooth_print

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.bluetooth_print
        pluginClass: BluetoothPrintPlugin
      ios:
        pluginClass: BluetoothPrintPlugin